import org.gradle.api.JavaVersion.VERSION_20

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */
plugins {
    java
}

group = "com.priyakdey"
version = "0.0.1"

java {
    sourceCompatibility = VERSION_20
    targetCompatibility = VERSION_20
}

repositories {
    mavenCentral()
}