/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    java
}

group = "com.priyakdey"
version = "0.0.1"

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType<JavaCompile> {
    dependsOn("verifyJavadocs")
}

apply<com.priyakdey.plugin.VerifyJavadocsPlugin>()